# Generated by Django 4.1.7 on 2023-03-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project Name', max_length=100),
        ),
    ]
