# Generated by Django 4.1.7 on 2023-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='titles',
            new_name='title',
        ),
    ]
